kind: pipeline
type: kubernetes
name: bender

metadata:
  namespace: bender

environment:
  hello: "hello all"
  

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo ${hello}
