global-variables:
  environment: &env
    hello: "hello all"

kind: pipeline
type: kubernetes
name: bender

metadata:
  namespace: bender

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - echo ${hello}
  environment:
    <<: *env
